name: Publish Python 🐍 distributions 📦 to PyPI and TestPyPI

on: push

jobs:
  build-n-publish:
    name: Build and publish Python 🐍 distributions 📦 to PyPI and TestPyPI
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Set up Python 3.6.2
      uses: actions/setup-python@v1
      with:
        python-version: 3.6.2
    - name: Install twine
      run: pip install twine
    - name: Build a binary wheel
      run: python setup.py sdist
    - name: Publish distribution 📦 to PyPI
      if: startsWith(github.ref, 'refs/tags')
      uses: pypa/gh-action-pypi-publish@master
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
# - name: Publish package
#   if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
#   uses: pypa/gh-action-pypi-publish@release/v1
#   with:
#     user: __token__
#     password: ${{ secrets.PYPI_API_TOKEN }}
